package io.github.mbannour.mongo.codecs

import io.github.mbannour.bson.macros.SubtypeDiscriminator

/** Turns the compile-time subtype metadata into the discriminator values a sealed hierarchy is stored under, applying the
  * `DiscriminatorStrategy` from the active [[CodecConfig]].
  *
  * This is the single place the choice is made. Two codecs write a discriminator - the sealed-hierarchy codec generated by
  * [[SealedTraitCodecGenerator]], and the concrete subtype codec generated by [[CaseClassCodecGenerator]] when
  * `CodecConfig.writeDiscriminator` is set - and a subtype encoded through one must be decodable through the other. Both resolve here so
  * they cannot disagree.
  *
  * The strategy is a runtime value, so the resolution has to happen at runtime too; what the macro settles at compile time is only the set
  * of subtypes and the name alternatives for each. See [[io.github.mbannour.bson.macros.SubtypeDiscriminator]].
  */
object DiscriminatorResolver:

  /** The discriminator value a single subtype is stored under.
    *
    * `@BsonDiscriminator` outranks the strategy: it names one subtype explicitly, while a strategy states a default for the hierarchy, and
    * the specific instruction wins. A `Custom` mapping that does not mention a subtype leaves it at its simple name, so a mapping need only
    * list the subtypes it actually renames.
    */
  private[mbannour] def discriminatorOf(subtype: SubtypeDiscriminator, strategy: DiscriminatorStrategy): String =
    subtype.annotated.getOrElse {
      strategy match
        case DiscriminatorStrategy.SimpleName         => subtype.simpleName
        case DiscriminatorStrategy.FullyQualifiedName => subtype.fullName
        case DiscriminatorStrategy.Custom(mapping)    => mapping.getOrElse(subtype.runtimeClass, subtype.simpleName)
    }

  /** Builds the discriminator-to-class map a sealed codec decodes through, under the given strategy.
    *
    * Rejects a strategy that cannot produce a readable document, rather than writing one that cannot be decoded:
    *
    *   - an empty resolved value is indistinguishable from no discriminator at all, exactly as an empty `@BsonDiscriminator` is;
    *   - two subtypes resolving to the same value would collapse into one map entry, so one subtype would silently disappear and documents
    *     holding it would decode as the other.
    *
    * Neither is reachable through `SimpleName` or `FullyQualifiedName`, which are derived from distinct compile-time names and are checked
    * for collision by the macro. Both are reachable through a hand-written `Custom` mapping, which is why they are checked here. The failure
    * happens while the registry is being built, before anything has been written.
    */
  private[mbannour] def discriminatorMap(
      subtypes: List[SubtypeDiscriminator],
      strategy: DiscriminatorStrategy,
      ownerName: String
  ): Map[String, Class[?]] =
    val resolved: List[(String, SubtypeDiscriminator)] =
      subtypes.map(subtype => discriminatorOf(subtype, strategy) -> subtype)

    resolved.find(_._1.isEmpty).foreach { (_, subtype) =>
      throw new IllegalArgumentException(
        s"Cannot build a codec for $ownerName: the discriminator strategy resolved an empty value for " +
          s"${subtype.runtimeClass.getName}. A document records only the discriminator, and an empty one is " +
          "indistinguishable from no discriminator at all, so it could never be decoded. " +
          "Give that subtype a non-empty value in the DiscriminatorStrategy.Custom mapping, or leave it out of the " +
          "mapping to store it under its simple name."
      )
    }

    val collisions = resolved.groupBy(_._1).filter(_._2.sizeIs > 1)

    collisions.toList.sortBy(_._1).headOption.foreach { (discriminator, entries) =>
      val names = entries.map(_._2.runtimeClass.getName).sorted.mkString(", ")
      throw new IllegalArgumentException(
        s"Cannot build a codec for $ownerName: the discriminator strategy resolved '$discriminator' for " +
          s"${entries.size} subtypes: $names. A document records only the discriminator, so decoding could not tell " +
          "them apart. Give each subtype a distinct value in the DiscriminatorStrategy.Custom mapping."
      )
    }

    resolved.map((discriminator, subtype) => discriminator -> subtype.runtimeClass).toMap
  end discriminatorMap
end DiscriminatorResolver
